"use client";

/*
 * كوّن وعيك · Build Your Awareness — the GENERATOR ENGINE.
 * ─────────────────────────────────────────────────────────────────────────────
 * Type ANY subject or role → موثوق forges a complete awareness map live:
 * overview · a mastery roadmap · core concepts · the strongest real tools ·
 * global standards · canonical books · online + offline communities · top
 * websites · do's & don'ts · live-update feeds. The committee fields are
 * instant, always-on presets. Any custom subject is generated by the AI
 * rotator via /api/kawwen-waayak — real, resolvable sources only (the One Law).
 */

import { useState } from "react";
import { useRTL } from "@/components/shared/rtl-provider";
import { PageNavigation } from "@/components/shared/page-navigation";
import {
  ArrowUpRight, ShieldCheck, GraduationCap, FlaskConical, Factory, TrendingUp,
  Cpu, BookOpen, Award, Users, Globe2, MapPin, Check, X, Radio, Sparkles,
  Wand2, Loader2, Route, Lightbulb,
} from "lucide-react";

const GOLD = "#BC9457", GOLDB = "#E4C583", INK = "#0a0e14";
const AR_DISPLAY = `'Reem Kufi','Readex Pro',serif`;
const EN_DISPLAY = `'Cinzel','Space Grotesk',serif`;

type BL = { en: string; ar: string };
type AItem = { name: string; en: string; ar: string; url: string | null };
type Preset = {
  id: string; icon: React.ComponentType<{ size?: number }>; accent: string;
  q: string; title: BL; role: BL; intro: BL;
  tech: AItem[]; standards: AItem[]; books: AItem[];
  online: AItem[]; sites: AItem[]; offline: AItem[];
  dos: BL[]; donts: BL[]; live: AItem[];
};
type AIDossier = {
  title: BL; overview: BL;
  roadmap: { label: BL; focus: BL }[]; concepts: BL[];
  tools: AItem[]; standards: AItem[]; books: AItem[];
  online: AItem[]; websites: AItem[]; offline: AItem[];
  dos: BL[]; donts: BL[]; live: AItem[];
};

const it = (name: string, en: string, ar: string, url: string | null = null): AItem => ({ name, en, ar, url });

/* Committee-tuned instant presets (curated real references — always work, no AI wait). */
const PRESETS: Preset[] = [
  {
    id: "consumer", icon: ShieldCheck, accent: "#E0806E", q: "Consumer protection",
    title: { en: "Consumer Protection", ar: "حماية المستهلك" },
    role: { en: "For the consumer-safety authority", ar: "لجهاز حماية المستهلك" },
    intro: { en: "Protecting people from unsafe products, fraud, and deceptive claims — with the global safety standards, recall systems, and consumer-rights bodies that define the field.", ar: "حماية الناس من المنتجات غير الآمنة والاحتيال والادّعاءات المضلّلة — بمعايير الأمان العالمية وأنظمة السحب وهيئات حقوق المستهلك." },
    tech: [it("EU Safety Gate (RAPEX)", "EU rapid alert for dangerous non-food products", "الإنذار السريع الأوروبي للمنتجات الخطرة", "https://ec.europa.eu/safety-gate-alerts"), it("US CPSC Recalls", "Live national product-recall database", "قاعدة بيانات سحب المنتجات", "https://www.cpsc.gov/Recalls"), it("GS1 traceability", "Trace a product to source across the supply chain", "تتبّع المنتج من المصدر", "https://www.gs1.org"), it("AI fraud & scam detection", "Detect scam ads, fake reviews, price fraud", "كشف الإعلانات المخادعة والمراجعات المزيّفة")],
    standards: [it("ISO 10377", "Consumer product safety — supplier guidelines", "سلامة منتجات المستهلك", "https://www.iso.org/standard/45967.html"), it("ISO 10393", "Consumer product recall — guidelines", "سحب منتجات المستهلك", "https://www.iso.org/standard/45968.html"), it("UN Guidelines for Consumer Protection", "The global reference framework (UNCTAD)", "الإطار المرجعي العالمي", "https://unctad.org/topic/competition-and-consumer-protection"), it("Egypt Law 181/2018", "The national consumer-protection statute", "قانون حماية المستهلك المصري")],
    books: [it("Consumer Protection Law", "Howells & Weatherill — the standard text", "هاولز وويذريل — المرجع الأساسي"), it("Nudge", "Thaler & Sunstein — choice architecture & disclosure", "ثالر وسنستاين — هندسة الاختيار"), it("Predictably Irrational", "Dan Ariely — how consumers are misled", "دان أريلي — إزّاي المستهلك بيتضلّل"), it("Trust Me, I'm Lying", "Ryan Holiday — deceptive marketing", "رايان هوليداي — التسويق المخادع")],
    online: [it("Consumers International", "Global federation of consumer groups", "الاتحاد العالمي لجمعيات المستهلك", "https://www.consumersinternational.org"), it("ISO COPOLCO", "ISO committee on consumer policy", "لجنة سياسة المستهلك في الأيزو", "https://www.iso.org/copolco.html"), it("OECD Consumer Policy", "Global consumer-policy guidance", "توجيهات سياسة المستهلك", "https://www.oecd.org/en/topics/consumer-protection.html")],
    sites: [it("BEUC", "The European Consumer Organisation", "المنظمة الأوروبية للمستهلكين", "https://www.beuc.eu"), it("Consumer Reports", "Independent product testing", "اختبار مستقل للمنتجات", "https://www.consumerreports.org"), it("FTC Consumer Advice", "Scam & fraud guidance", "إرشادات الاحتيال", "https://consumer.ftc.gov")],
    offline: [it("ISO COPOLCO plenary", "Annual global consumer-standards forum", "منتدى معايير المستهلك السنوي"), it("Consumers International Congress", "The worldwide consumer-movement summit", "قمة حركة المستهلك"), it("National testing labs & hotlines", "On-ground product testing & complaints", "معامل اختبار وخطوط شكاوى")],
    dos: [{ en: "Verify every product claim against a named standard/test", ar: "تحقّق من كل ادّعاء مقابل معيار مُسمّى" }, { en: "Trace recalls to the primary source", ar: "ارجع السحب لمصدره الأصلي" }, { en: "Publish transparent, resolvable evidence", ar: "انشر أدلّة شفّافة يقدر المستهلك يراجعها" }],
    donts: [{ en: "Never rely on a seller's self-declaration alone", ar: "متعتمدش على إقرار البائع لوحده" }, { en: "Don't act on a viral post without provenance", ar: "متتحرّكش على بوست منتشر من غير مصدر" }, { en: "Don't confuse marketing with a certified test", ar: "متخلطش الادّعاء التسويقي بالاختبار المعتمد" }],
    live: [it("Safety Gate weekly alerts", "", "", "https://ec.europa.eu/safety-gate-alerts"), it("OECD consumer newsroom", "", "", "https://www.oecd.org/en/topics/consumer-protection.html")],
  },
  {
    id: "training", icon: GraduationCap, accent: "#4FB6A8", q: "Technical vocational training (TVET)",
    title: { en: "Technical Training", ar: "التدريب الفني" },
    role: { en: "For the technical-training director", ar: "لمدير التدريب الفني" },
    intro: { en: "Building real skill that transfers to the job — the learning-science, the TVET standards, and the platforms that make training measurable and durable.", ar: "بناء مهارة حقيقية بتنتقل للشغل — علم التعلّم ومعايير التدريب المهني والمنصّات اللي بتخلّيه قابل للقياس." },
    tech: [it("xAPI & SCORM", "Standards to track what a learner actually did", "معايير تتبّع اللي المتعلّم عمله", "https://xapi.com"), it("Moodle / Canvas LMS", "Open, proven learning platforms", "منصّات تعلّم مفتوحة ومجرّبة", "https://moodle.org"), it("VR / simulation training", "Hands-on practice for high-risk skills", "تدريب عملي للمهارات الخطرة"), it("Micro-credentials", "Stackable, verifiable skill certificates", "شهادات مهارة قابلة للتحقّق")],
    standards: [it("ISO 21001", "Management system for educational orgs", "نظام إدارة للمؤسّسات التعليمية", "https://www.iso.org/standard/66266.html"), it("ISO 29993", "Learning services outside formal education", "خدمات التعلّم خارج التعليم النظامي", "https://www.iso.org/standard/70357.html"), it("UNESCO-UNEVOC TVET", "Global reference for vocational education", "المرجع العالمي للتعليم المهني", "https://unevoc.unesco.org"), it("CEDEFOP frameworks", "EU competence & qualification frameworks", "أطر الكفاءات الأوروبية", "https://www.cedefop.europa.eu")],
    books: [it("Make It Stick", "Brown, Roediger, McDaniel — durable learning", "علم التعلّم الدائم"), it("Design for How People Learn", "Julie Dirksen — instructional design", "التصميم التعليمي الصح"), it("The Adult Learner", "Malcolm Knowles — andragogy", "نولز — أساس تدريب الكبار"), it("Training from the Back of the Room", "Sharon Bowman — brain-based delivery", "توصيل قائم على علم الدماغ")],
    online: [it("ATD", "Largest training & development body", "أكبر هيئة تدريب وتطوير", "https://www.td.org"), it("UNESCO-UNEVOC network", "Global TVET practitioner community", "شبكة ممارسي التعليم المهني", "https://unevoc.unesco.org"), it("ILO Skills", "International skills & employability", "مهارات العمل الدولية", "https://www.ilo.org/skills")],
    sites: [it("eLearning Industry", "Practitioner articles, tools, trends", "مقالات وأدوات واتجاهات", "https://elearningindustry.com"), it("City & Guilds", "Global vocational qualifications", "مؤهّلات مهنية عالمية", "https://www.cityandguilds.com"), it("OER Commons", "Free open training resources", "مصادر تدريب مفتوحة", "https://www.oercommons.org")],
    offline: [it("ATD International Conference", "The world's biggest training gathering", "أكبر تجمّع تدريب"), it("WorldSkills", "Global vocational-skills championship", "بطولة المهارات المهنية العالمية"), it("Regional TVET centres", "Workshops & apprenticeships", "ورش وتلمذة صناعية")],
    dos: [{ en: "Design to a competency, then measure transfer to the job", ar: "صمّم لكفاءة وقِس انتقالها للشغل" }, { en: "Use spacing, retrieval, and real practice", ar: "استخدم التباعد والاسترجاع والتطبيق" }, { en: "Certify with verifiable, stackable credentials", ar: "اعتمد بشهادات قابلة للتحقّق" }],
    donts: [{ en: "Don't confuse 'time in a course' with skill", ar: "متخلطش وقت الكورس بالمهارة" }, { en: "Avoid one-off lectures with no practice", ar: "بلاش محاضرات من غير تطبيق" }, { en: "Don't skip a baseline + post measure", ar: "متفوّتش القياس القبلي والبعدي" }],
    live: [it("ATD Insights", "", "", "https://www.td.org/insights"), it("CEDEFOP news", "", "", "https://www.cedefop.europa.eu/en/news")],
  },
  {
    id: "research", icon: FlaskConical, accent: "#7FA8E0", q: "Research to industry transfer",
    title: { en: "Research → Industry", ar: "ربط البحث بالصناعة" },
    role: { en: "For the research-to-industry lead", ar: "لأستاذ ربط البحث بالصناعة" },
    intro: { en: "Turning rigorous research into deployed products — the maturity models, innovation standards, and tech-transfer bodies that bridge the lab and the market.", ar: "تحويل البحث الدقيق لمنتجات منشورة — نماذج النضج ومعايير الابتكار وهيئات نقل التكنولوجيا." },
    tech: [it("Technology Readiness Levels (TRL 1–9)", "NASA/EU scale for research→product maturity", "مقياس نضج من البحث للمنتج", "https://www.nasa.gov"), it("Espacenet / Google Patents", "Global prior-art & patent search", "بحث براءات عالمي", "https://worldwide.espacenet.com"), it("Open-innovation platforms", "Challenge-driven academia–industry matching", "ربط الأكاديميا بالصناعة"), it("Digital twin & simulation", "De-risk a lab result before the factory", "تقليل المخاطر قبل الإنتاج")],
    standards: [it("ISO 56000 series", "Innovation management systems", "أنظمة إدارة الابتكار", "https://www.iso.org/committee/4587737.html"), it("OECD Frascati Manual", "Global standard for measuring R&D", "معيار قياس البحث والتطوير", "https://www.oecd.org"), it("OECD Oslo Manual", "The standard for measuring innovation", "معيار قياس الابتكار", "https://www.oecd.org"), it("Bayh-Dole framework", "The tech-transfer model behind US innovation", "نموذج نقل التكنولوجيا")],
    books: [it("The Innovator's Dilemma", "Clayton Christensen — disruptive innovation", "كريستنسن — الابتكار المُزعزِع"), it("Crossing the Chasm", "Geoffrey Moore — tech to mainstream markets", "مور — الوصول للسوق"), it("The Lean Startup", "Eric Ries — validated learning", "ريس — التعلّم المُثبَت"), it("Loonshots", "Safi Bahcall — nurturing breakthroughs", "بهكال — رعاية الاختراقات")],
    online: [it("AUTM", "Association of University Technology Managers", "جمعية نقل تكنولوجيا الجامعات", "https://autm.net"), it("WIPO", "World IP org — patents & transfer", "المنظمة العالمية للملكية الفكرية", "https://www.wipo.int"), it("ASTP", "European knowledge-transfer community", "مجتمع نقل المعرفة الأوروبي", "https://www.astp4kt.eu")],
    sites: [it("Horizon Europe", "EU research→innovation funding", "تمويل البحث والابتكار الأوروبي", "https://research-and-innovation.ec.europa.eu"), it("Fraunhofer", "The gold-standard applied-research model", "النموذج الذهبي للبحث التطبيقي", "https://www.fraunhofer.de/en.html"), it("Nature Careers", "Research-to-industry insight", "رؤى ربط البحث بالصناعة", "https://www.nature.com/nature/careers")],
    offline: [it("AUTM Annual Meeting", "Global tech-transfer gathering", "التجمّع العالمي لنقل التكنولوجيا"), it("University incubators & TTOs", "Offices that commercialise research", "مكاتب تسويق البحث"), it("Industry–academia consortia", "Joint labs bridging both worlds", "معامل مشتركة")],
    dos: [{ en: "State the TRL honestly + the path to raise it", ar: "حدّد مستوى النضج بصدق وطريق رفعه" }, { en: "Search prior art before claiming novelty", ar: "ابحث حالة التقنية قبل ادّعاء الجِدّة" }, { en: "Design studies so results reproduce", ar: "صمّم الدراسة عشان النتائج تتكرّر" }],
    donts: [{ en: "Don't present a prototype as market-ready", ar: "متقدّمش نموذج كإنه جاهز للسوق" }, { en: "Don't skip IP/prior-art diligence", ar: "متفوّتش فحص الملكية الفكرية" }, { en: "Don't claim impact you haven't measured", ar: "متدّعيش أثر ما قِستوش" }],
    live: [it("WIPO news", "", "", "https://www.wipo.int/pressroom/en"), it("Horizon Europe updates", "", "", "https://research-and-innovation.ec.europa.eu/news_en")],
  },
  {
    id: "automotive", icon: Factory, accent: "#D6A94E", q: "Automotive manufacturing",
    title: { en: "Automotive Manufacturing", ar: "تصنيع السيارات" },
    role: { en: "For the automotive-manufacturing GM", ar: "لمدير عام تصنيع السيارات" },
    intro: { en: "Building cars right and safe at scale — the quality systems, functional-safety standards, and lean methods that run the world's automotive plants.", ar: "تصنيع سيارات صح وآمنة بكميات كبيرة — أنظمة الجودة ومعايير السلامة ومنهجيات الـLean." },
    tech: [it("MES + Digital Twin", "Real-time execution + a virtual model of the line", "تنفيذ لحظي ونموذج افتراضي للخط"), it("Industry 4.0 / IIoT", "Connected sensors, predictive maintenance", "حسّاسات متّصلة وصيانة تنبّؤية"), it("Robotics & cobots", "Precision assembly, human-safe automation", "تجميع دقيق وأتمتة آمنة"), it("PLM (Teamcenter)", "Product-lifecycle management", "إدارة دورة حياة المنتج")],
    standards: [it("IATF 16949", "THE automotive quality-management standard", "معيار إدارة الجودة الأول في السيارات", "https://www.iatfglobaloversight.org"), it("ISO 26262", "Functional safety of road vehicles", "سلامة الأداء الوظيفي للمركبات", "https://www.iso.org/standard/68383.html"), it("APQP · PPAP · FMEA", "Core quality-planning & risk tools (AIAG-VDA)", "أدوات تخطيط الجودة والمخاطر", "https://www.aiag.org"), it("ISO/SAE 21434", "Automotive cybersecurity engineering", "الأمن السيبراني للسيارات", "https://www.iso.org/standard/70918.html")],
    books: [it("The Toyota Way", "Jeffrey Liker — the lean-production bible", "لايكر — إنجيل الإنتاج الرشيق"), it("The Machine That Changed the World", "Womack, Jones, Roos — lean vs mass production", "الـLean ضد الإنتاج الضخم"), it("Lean Thinking", "Womack & Jones — eliminating waste", "التخلّص من الهدر"), it("The Goal", "Goldratt — theory of constraints", "جولدرات — نظرية القيود")],
    online: [it("SAE International", "Mobility-engineering standards & community", "معايير هندسة التنقّل", "https://www.sae.org"), it("AIAG", "Automotive Industry Action Group", "مجموعة عمل صناعة السيارات", "https://www.aiag.org"), it("VDA (Germany)", "German automotive quality authority", "هيئة جودة السيارات الألمانية", "https://www.vda.de/en")],
    sites: [it("IATF Global Oversight", "The IATF 16949 authority & rules", "مرجع معيار IATF 16949", "https://www.iatfglobaloversight.org"), it("Automotive News", "Industry & manufacturing trends", "أخبار واتجاهات التصنيع", "https://www.autonews.com"), it("Lean Enterprise Institute", "Home of lean-manufacturing practice", "بيت التصنيع الرشيق", "https://www.lean.org")],
    offline: [it("IAA / auto trade shows", "Global manufacturing & supplier expos", "معارض التصنيع والموردين"), it("Gemba walks & kaizen", "On-the-floor continuous improvement", "التحسين المستمر في المصنع"), it("Supplier audits (VDA 6.3)", "On-site process audits", "تدقيق العمليات في الموقع")],
    dos: [{ en: "Run APQP/PPAP before mass production", ar: "نفّذ APQP/PPAP قبل الإنتاج الكمّي" }, { en: "Design safety in (ISO 26262) from day one", ar: "ادمج السلامة من البداية" }, { en: "Chase waste with lean; measure OEE", ar: "طارد الهدر وقِس كفاءة المعدّات" }],
    donts: [{ en: "Don't ship without a closed FMEA", ar: "متشحنش من غير FMEA مقفول" }, { en: "Don't treat a supplier cert as an audit", ar: "شهادة المورّد مش بديل عن التدقيق" }, { en: "Don't optimise one station, starve the line", ar: "متحسّنش محطّة وتجوّع الخط" }],
    live: [it("SAE news", "", "", "https://www.sae.org/news"), it("IATF communiqués", "", "", "https://www.iatfglobaloversight.org/news")],
  },
  {
    id: "business", icon: TrendingUp, accent: "#84C79B", q: "Business development",
    title: { en: "Business Development", ar: "تطوير الأعمال" },
    role: { en: "For the business-development lead", ar: "لقائد تطوير الأعمال" },
    intro: { en: "Turning a real product into a growing business — the strategy frameworks, growth playbooks, and go-to-market communities that scale value.", ar: "تحويل منتج حقيقي لبزنس بينمو — أطر الاستراتيجية ودلائل النمو ومجتمعات النزول للسوق." },
    tech: [it("CRM (HubSpot / Salesforce)", "Pipeline, relationships, revenue tracking", "خطّ الصفقات والعلاقات والإيراد", "https://www.hubspot.com"), it("Analytics (Amplitude / Mixpanel)", "Measure activation, retention, funnels", "قياس التفعيل والاحتفاظ"), it("AARRR pirate metrics", "Acquisition→Activation→Retention→Referral→Revenue", "مقاييس النمو الخمسة"), it("No-code + AI outreach", "Ship experiments & reach fast", "أطلق تجارب ووصول بسرعة")],
    standards: [it("Business Model Canvas", "Osterwalder — the model-design standard", "أوسترفالدر — أداة تصميم النموذج", "https://www.strategyzer.com/library/the-business-model-canvas"), it("Value Proposition Design", "Fit product to a real customer job", "مطابقة المنتج لحاجة العميل", "https://www.strategyzer.com/library/the-value-proposition-canvas"), it("Porter's Five Forces", "Standard industry-competition analysis", "تحليل تنافس الصناعة"), it("OKRs", "Objectives & Key Results — outcome alignment", "الأهداف والنتائج الرئيسية")],
    books: [it("Crossing the Chasm", "Geoffrey Moore — mainstreaming a product", "مور — الوصول للسوق الرئيسي"), it("The Lean Startup", "Eric Ries — build-measure-learn", "ريس — ابنِ-قِس-تعلّم"), it("Blue Ocean Strategy", "Kim & Mauborgne — uncontested markets", "سوق بلا منافسة"), it("Traction", "Weinberg & Mares — 19 growth channels", "19 قناة للنمو")],
    online: [it("Y Combinator Library", "Free startup & growth playbooks", "دلائل الشركات الناشئة", "https://www.ycombinator.com/library"), it("First Round Review", "Deeply practical operator essays", "مقالات عملية من مؤسّسين", "https://review.firstround.com"), it("Harvard Business Review", "The strategy & management standard", "المرجع في الاستراتيجية", "https://hbr.org")],
    sites: [it("Strategyzer", "Canvas tools & business-design courses", "أدوات الكانفس ودورات الأعمال", "https://www.strategyzer.com"), it("Lenny's Newsletter", "Product & growth, weekly", "المنتج والنمو أسبوعياً", "https://www.lennysnewsletter.com"), it("CB Insights", "Market & competitive intelligence", "ذكاء السوق والمنافسة", "https://www.cbinsights.com")],
    offline: [it("Web Summit / Slush", "The world's biggest startup gatherings", "أكبر تجمّعات الشركات الناشئة"), it("Startup Grind chapters", "Local founder & BD meetups", "لقاءات المؤسّسين محلياً"), it("Industry trade shows", "Partnerships, leads, market signal", "شراكات وعملاء وإشارات سوق")],
    dos: [{ en: "Validate the customer job before you scale", ar: "تحقّق من حاجة العميل قبل التوسّع" }, { en: "Pick 1–2 growth channels and go deep", ar: "اختار قناة أو اتنين وتعمّق" }, { en: "Tie every activity to an outcome metric", ar: "اربط كل نشاط بمقياس نتيجة" }],
    donts: [{ en: "Don't scale with no proven retention", ar: "متوسّعش من غير احتفاظ مُثبَت" }, { en: "Don't chase 19 channels at once", ar: "متجريش ورا 19 قناة مرة واحدة" }, { en: "Don't confuse activity with traction", ar: "متخلطش النشاط بالنمو" }],
    live: [it("HBR latest", "", "", "https://hbr.org/latest"), it("First Round Review", "", "", "https://review.firstround.com")],
  },
];

export default function KawwenWaayakPage() {
  const { isRTL } = useRTL();
  const t = (en: string, ar: string) => (isRTL ? ar : en);
  const b = (x: BL) => (isRTL ? x.ar : x.en);
  const dir: "rtl" | "ltr" = isRTL ? "rtl" : "ltr";

  const [activePreset, setActivePreset] = useState(0);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [ai, setAi] = useState<AIDossier | null>(null);

  async function generate(subject: string) {
    const s = subject.trim();
    if (!s || loading) return;
    setLoading(true); setErr(null);
    try {
      const r = await fetch("/api/kawwen-waayak", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject: s }) });
      const j = await r.json();
      if (!r.ok || !j?.dossier) throw new Error(j?.error || "generation failed");
      setAi(j.dossier as AIDossier);
      if (typeof window !== "undefined") document.getElementById("kw-result")?.scrollIntoView({ behavior: "smooth", block: "start" });
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }

  const preset = PRESETS[activePreset];
  const accent = ai ? GOLD : preset.accent;

  // Normalised view for the ONE renderer.
  const titleTxt = ai ? b(ai.title) : b(preset.title);
  const roleTxt = ai ? t("Generated by موثوق · real sources", "مولّد بموثوق · مصادر حقيقية") : b(preset.role);
  const introTxt = ai ? b(ai.overview) : b(preset.intro);
  const sections: { icon: React.ComponentType<{ size?: number }>; label: BL; items: AItem[] }[] = [
    { icon: Cpu, label: { en: "Strong & trending tools", ar: "أقوى الأدوات والتقنيات" }, items: ai ? ai.tools : preset.tech },
    { icon: Award, label: { en: "Global standards", ar: "المعايير العالمية" }, items: ai ? ai.standards : preset.standards },
    { icon: BookOpen, label: { en: "Canonical books", ar: "أهم الكتب" }, items: ai ? ai.books : preset.books },
    { icon: Users, label: { en: "Online communities", ar: "المجتمعات أونلاين" }, items: ai ? ai.online : preset.online },
    { icon: Globe2, label: { en: "Top websites", ar: "أقوى المواقع" }, items: ai ? ai.websites : preset.sites },
    { icon: MapPin, label: { en: "Offline communities", ar: "المجتمعات على أرض الواقع" }, items: ai ? ai.offline : preset.offline },
  ];
  const dos = ai ? ai.dos : preset.dos;
  const donts = ai ? ai.donts : preset.donts;
  const live = ai ? ai.live : preset.live;

  return (
    <div dir={dir} style={{ background: INK, color: "var(--text-primary, #e8eef7)", minHeight: "100vh", overflowX: "hidden" }}>
      <style>{`
        .kw-shim { background: linear-gradient(100deg,#8a5f22,${GOLD} 20%,${GOLDB} 38%,#fff 48%,${GOLDB} 60%,${GOLD} 78%,#8a5f22); background-size:220% auto; -webkit-background-clip:text; background-clip:text; -webkit-text-fill-color:transparent; animation:kwsh 6s linear infinite; }
        @keyframes kwsh { to { background-position:-220% 50%; } }
        .kw-item { transition: transform .18s, background .18s; }
        .kw-item:hover { transform: translateX(${isRTL ? "-3px" : "3px"}); }
        .kw-gen:hover { transform: translateY(-2px); filter:brightness(1.06); }
        .kw-gen { transition: transform .2s, filter .2s; }
        .kw-spin { animation: kwspin 1s linear infinite; } @keyframes kwspin { to { transform: rotate(360deg); } }
        .kw-pulse { animation: kwpulse 1.4s ease-in-out infinite; } @keyframes kwpulse { 0%,100%{opacity:.5} 50%{opacity:1} }
        @media (prefers-reduced-motion: reduce){ .kw-shim,.kw-spin,.kw-pulse{animation:none} }
      `}</style>

      {/* HERO */}
      <section style={{ textAlign: "center", padding: "clamp(2.6rem,7vh,4.6rem) clamp(1rem,4vw,2.5rem) 1rem", background: `radial-gradient(120% 90% at 50% 0%, color-mix(in srgb, ${GOLD} 16%, ${INK}), ${INK} 70%)` }}>
        <div style={{ display: "inline-flex", alignItems: "center", gap: ".5rem", fontFamily: EN_DISPLAY, letterSpacing: ".3em", textTransform: "uppercase", fontSize: ".72rem", color: GOLD }}>
          <Sparkles size={15} /> {t("A موثوق engine", "محرّك من موثوق")}
        </div>
        <h1 className="kw-shim" style={{ fontFamily: AR_DISPLAY, fontWeight: 700, fontSize: "clamp(3rem,11vw,6rem)", lineHeight: 1, margin: ".4rem 0 0" }}>كوّن وعيك</h1>
        <div style={{ fontFamily: EN_DISPLAY, letterSpacing: ".42em", fontSize: "clamp(.65rem,2vw,.9rem)", color: "rgba(245,238,222,.66)", marginTop: ".5rem" }}>BUILD YOUR AWARENESS</div>
        <p style={{ maxWidth: 640, margin: "1.2rem auto 0", color: "rgba(245,238,222,.85)", fontSize: "clamp(1rem,2.5vw,1.22rem)", lineHeight: 1.65 }}>
          {t("Name any field. موثوق forges a complete awareness map — the strongest real tools, the world's standards, the canonical books, the communities, and the path to mastery.", "قول أي مجال. موثوق بيكوّنلك خريطة وعي كاملة — أقوى الأدوات الحقيقية، ومعايير العالم، وأهم الكتب، والمجتمعات، وطريق الإتقان.")}
        </p>
      </section>

      {/* ENGINE BAR */}
      <div style={{ maxWidth: 820, margin: "0 auto", padding: "0 clamp(1rem,4vw,2.5rem)" }}>
        <div style={{ display: "flex", gap: ".6rem", flexDirection: isRTL ? "row-reverse" : "row", alignItems: "stretch" }}>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") generate(input); }}
            placeholder={t("Type any subject or role — e.g. cybersecurity, nursing, solar energy…", "اكتب أي مجال أو وظيفة — مثلاً الأمن السيبراني، التمريض، الطاقة الشمسية…")}
            style={{ flex: 1, minWidth: 0, padding: "1rem 1.1rem", borderRadius: 14, fontSize: "1rem", fontFamily: "inherit",
              background: "color-mix(in srgb, var(--text-primary) 6%, transparent)", color: "var(--text-primary)",
              border: `1px solid color-mix(in srgb, ${GOLD} 40%, transparent)`, outline: "none", textAlign: isRTL ? "right" : "left" }}
          />
          <button type="button" onClick={() => generate(input)} disabled={loading || !input.trim()} className="kw-gen"
            style={{ appearance: "none", cursor: loading || !input.trim() ? "default" : "pointer", display: "inline-flex", alignItems: "center", gap: ".5rem",
              padding: "1rem 1.5rem", borderRadius: 14, fontWeight: 800, fontSize: "1rem", color: "#0a0a0a", whiteSpace: "nowrap",
              background: `linear-gradient(135deg, ${GOLDB}, ${GOLD} 55%, #8a5f22)`, border: `1px solid ${GOLDB}`, opacity: loading || !input.trim() ? .6 : 1 }}>
            {loading ? <Loader2 size={18} className="kw-spin" /> : <Wand2 size={18} />}
            {t("Build", "كوّن")}
          </button>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: ".5rem", marginTop: ".8rem", flexWrap: "wrap", justifyContent: "center", fontSize: ".82rem", color: "var(--text-secondary)" }}>
          <ShieldCheck size={14} style={{ color: GOLDB }} /> {t("Real, resolvable sources only — the One Law.", "مصادر حقيقية تقدر ترجعلها — القانون الواحد.")}
        </div>

        {/* presets */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: ".55rem", justifyContent: "center", marginTop: "1.2rem" }}>
          <span style={{ alignSelf: "center", fontSize: ".8rem", color: "var(--text-secondary)" }}>{t("Instant:", "جاهز:")}</span>
          {PRESETS.map((p, i) => {
            const Icon = p.icon; const on = !ai && i === activePreset;
            return (
              <button key={p.id} type="button" onClick={() => { setAi(null); setErr(null); setActivePreset(i); }}
                style={{ appearance: "none", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: ".4rem", padding: ".5rem .85rem", borderRadius: 999, fontFamily: "inherit", fontSize: ".82rem", fontWeight: 600,
                  color: on ? "#0a0a0a" : "var(--text-primary)", background: on ? `linear-gradient(135deg,${p.accent},color-mix(in srgb,${p.accent} 70%,#000))` : "color-mix(in srgb, var(--text-primary) 5%, transparent)",
                  border: `1px solid ${on ? p.accent : "color-mix(in srgb, var(--text-primary) 14%, transparent)"}` }}>
                <Icon size={15} /> {b(p.title)}
              </button>
            );
          })}
        </div>
        {err && <div style={{ marginTop: "1rem", padding: ".8rem 1rem", borderRadius: 12, textAlign: "center", color: "#e07a70", background: "color-mix(in srgb,#c0483c 12%,transparent)", border: "1px solid color-mix(in srgb,#c0483c 40%,transparent)", fontSize: ".9rem" }}>
          {t("The engine is busy — try again in a moment, or pick an instant field above.", "المحرّك مشغول — جرّب تاني بعد لحظة، أو اختار مجال جاهز فوق.")}
        </div>}
      </div>

      {/* LOADING */}
      {loading && (
        <div style={{ textAlign: "center", padding: "clamp(2.5rem,7vh,4rem) 1rem" }}>
          <Loader2 size={38} className="kw-spin" style={{ color: GOLD }} />
          <p className="kw-pulse" style={{ fontFamily: AR_DISPLAY, fontSize: "1.3rem", color: GOLDB, marginTop: "1rem" }}>{t("Forging your awareness map…", "بنكوّن خريطة وعيك…")}</p>
          <p style={{ color: "var(--text-secondary)", fontSize: ".85rem", marginTop: ".3rem" }}>{t("Gathering the strongest real tools, standards, books & communities.", "بنجمع أقوى الأدوات والمعايير والكتب والمجتمعات الحقيقية.")}</p>
        </div>
      )}

      {/* RESULT */}
      {!loading && (
      <section id="kw-result" style={{ maxWidth: 1120, margin: "0 auto", padding: "clamp(1.6rem,4vh,2.6rem) clamp(1rem,4vw,2.5rem) clamp(3rem,8vh,5rem)" }}>
        {/* intro band */}
        <div style={{ padding: "clamp(1.3rem,3vw,2rem)", borderRadius: 20, marginBottom: "1.5rem",
          background: `linear-gradient(160deg, color-mix(in srgb, ${accent} 16%, var(--bg-card,#10141c)), var(--bg-card,#0c1017))`,
          border: `1px solid color-mix(in srgb, ${accent} 45%, transparent)`, textAlign: isRTL ? "right" : "left" }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: ".5rem", fontFamily: EN_DISPLAY, letterSpacing: ".14em", textTransform: "uppercase", fontSize: ".72rem", color: accent }}>
            {ai ? <Sparkles size={16} /> : <preset.icon size={16} />} {roleTxt}
          </div>
          <h2 style={{ fontFamily: AR_DISPLAY, fontSize: "clamp(1.6rem,4.5vw,2.4rem)", margin: ".4rem 0 .5rem", color: "var(--text-primary)" }}>{titleTxt}</h2>
          <p style={{ margin: 0, color: "var(--text-secondary)", maxWidth: 760, lineHeight: 1.6 }}>{introTxt}</p>
        </div>

        {/* AI extras: roadmap + concepts */}
        {ai && ai.roadmap?.length > 0 && (
          <div style={{ display: "grid", gridTemplateColumns: `repeat(auto-fit, minmax(200px, 1fr))`, gap: ".9rem", marginBottom: "1.5rem" }}>
            {ai.roadmap.map((r, i) => (
              <div key={i} style={{ padding: "1.1rem", borderRadius: 16, background: "var(--bg-card,#0f131b)", border: `1px solid color-mix(in srgb,${GOLD} 24%,transparent)`, textAlign: isRTL ? "right" : "left" }}>
                <div style={{ display: "flex", alignItems: "center", gap: ".5rem", color: GOLD, marginBottom: ".4rem", flexDirection: isRTL ? "row-reverse" : "row" }}>
                  <Route size={16} /><span style={{ fontFamily: EN_DISPLAY, fontSize: ".7rem", letterSpacing: ".1em", textTransform: "uppercase" }}>{t(`Stage ${i + 1}`, `مرحلة ${i + 1}`)}</span>
                </div>
                <div style={{ fontWeight: 800, color: "var(--text-primary)", marginBottom: ".2rem" }}>{b(r.label)}</div>
                <div style={{ color: "var(--text-secondary)", fontSize: ".85rem", lineHeight: 1.4 }}>{b(r.focus)}</div>
              </div>
            ))}
          </div>
        )}
        {ai && ai.concepts?.length > 0 && (
          <div style={{ padding: "1.2rem 1.3rem", borderRadius: 16, marginBottom: "1.5rem", background: "var(--bg-card,#0f131b)", border: `1px solid color-mix(in srgb,${GOLD} 24%,transparent)` }}>
            <div style={{ display: "flex", alignItems: "center", gap: ".5rem", color: GOLD, marginBottom: ".7rem", flexDirection: isRTL ? "row-reverse" : "row" }}>
              <Lightbulb size={17} /><span style={{ fontWeight: 800, color: "var(--text-primary)" }}>{t("Core concepts to master", "المفاهيم الأساسية اللي لازم تتقنها")}</span>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: ".5rem", justifyContent: isRTL ? "flex-end" : "flex-start" }}>
              {ai.concepts.map((c, i) => (
                <span key={i} style={{ padding: ".4rem .8rem", borderRadius: 999, fontSize: ".85rem", color: "var(--text-primary)", background: `color-mix(in srgb,${GOLD} 10%,transparent)`, border: `1px solid color-mix(in srgb,${GOLD} 30%,transparent)` }}>{b(c)}</span>
              ))}
            </div>
          </div>
        )}

        {/* resource sections */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "clamp(1rem,2.5vw,1.4rem)" }}>
          {sections.map((sec, si) => {
            const Icon = sec.icon;
            return (
              <div key={si} style={{ padding: "1.3rem", borderRadius: 18, background: "var(--bg-card, #0f131b)", border: "1px solid color-mix(in srgb, var(--text-primary) 12%, transparent)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: ".6rem", marginBottom: ".9rem", color: accent, flexDirection: isRTL ? "row-reverse" : "row" }}>
                  <Icon size={19} /><span style={{ fontWeight: 800, fontSize: "1.02rem", color: "var(--text-primary)" }}>{b(sec.label)}</span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: ".5rem" }}>
                  {sec.items?.map((item, ii) => {
                    const note = isRTL ? item.ar : item.en;
                    const inner = (
                      <>
                        <div style={{ minWidth: 0, textAlign: isRTL ? "right" : "left" }}>
                          <div style={{ fontWeight: 700, color: "var(--text-primary)", fontSize: ".95rem" }}>{item.name}</div>
                          {note ? <div style={{ color: "var(--text-secondary)", fontSize: ".82rem", lineHeight: 1.4 }}>{note}</div> : null}
                        </div>
                        {item.url ? <ArrowUpRight size={15} style={{ color: accent, flexShrink: 0 }} /> : null}
                      </>
                    );
                    const style: React.CSSProperties = { display: "flex", alignItems: "center", justifyContent: "space-between", gap: ".7rem", padding: ".6rem .75rem", borderRadius: 12, textDecoration: "none", color: "inherit", background: `color-mix(in srgb, ${accent} 7%, transparent)`, border: `1px solid color-mix(in srgb, ${accent} 20%, transparent)`, flexDirection: isRTL ? "row-reverse" : "row" };
                    return item.url ? <a key={ii} className="kw-item" href={item.url} target="_blank" rel="noopener noreferrer" style={style}>{inner}</a> : <div key={ii} className="kw-item" style={style}>{inner}</div>;
                  })}
                </div>
              </div>
            );
          })}
        </div>

        {/* DO / DON'T */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "clamp(1rem,2.5vw,1.4rem)", marginTop: "1.4rem" }}>
          <div style={{ padding: "1.3rem", borderRadius: 18, background: "color-mix(in srgb, #3ea06e 10%, var(--bg-card,#0f131b))", border: "1px solid color-mix(in srgb, #3ea06e 40%, transparent)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: ".5rem", marginBottom: ".8rem", color: "#5cc98d", flexDirection: isRTL ? "row-reverse" : "row" }}><Check size={19} /><span style={{ fontWeight: 800, color: "var(--text-primary)" }}>{t("Do", "اعمل")}</span></div>
            {dos?.map((d, i) => (<div key={i} style={{ display: "flex", gap: ".5rem", padding: ".35rem 0", color: "var(--text-secondary)", flexDirection: isRTL ? "row-reverse" : "row", textAlign: isRTL ? "right" : "left" }}><Check size={16} style={{ color: "#5cc98d", flexShrink: 0, marginTop: 3 }} /><span>{b(d)}</span></div>))}
          </div>
          <div style={{ padding: "1.3rem", borderRadius: 18, background: "color-mix(in srgb, #c0483c 10%, var(--bg-card,#0f131b))", border: "1px solid color-mix(in srgb, #c0483c 40%, transparent)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: ".5rem", marginBottom: ".8rem", color: "#e07a70", flexDirection: isRTL ? "row-reverse" : "row" }}><X size={19} /><span style={{ fontWeight: 800, color: "var(--text-primary)" }}>{t("Don't", "متعملش")}</span></div>
            {donts?.map((d, i) => (<div key={i} style={{ display: "flex", gap: ".5rem", padding: ".35rem 0", color: "var(--text-secondary)", flexDirection: isRTL ? "row-reverse" : "row", textAlign: isRTL ? "right" : "left" }}><X size={16} style={{ color: "#e07a70", flexShrink: 0, marginTop: 3 }} /><span>{b(d)}</span></div>))}
          </div>
        </div>

        {/* LIVE */}
        {live?.length > 0 && (
          <div style={{ marginTop: "1.4rem", padding: "1.2rem 1.3rem", borderRadius: 18, background: "var(--bg-card,#0f131b)", border: `1px solid color-mix(in srgb, ${accent} 30%, transparent)` }}>
            <div style={{ display: "flex", alignItems: "center", gap: ".55rem", marginBottom: ".8rem", color: accent, flexDirection: isRTL ? "row-reverse" : "row" }}><Radio size={18} /><span style={{ fontWeight: 800, color: "var(--text-primary)" }}>{t("Live updates — stay current", "تحديثات حيّة — خليك متابع")}</span></div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: ".6rem", justifyContent: isRTL ? "flex-end" : "flex-start" }}>
              {live.map((item, i) => item.url ? (
                <a key={i} href={item.url} target="_blank" rel="noopener noreferrer" style={{ display: "inline-flex", alignItems: "center", gap: ".4rem", padding: ".5rem .9rem", borderRadius: 999, textDecoration: "none", color: "var(--text-primary)", background: `color-mix(in srgb, ${accent} 10%, transparent)`, border: `1px solid color-mix(in srgb, ${accent} 32%, transparent)`, fontSize: ".85rem", fontWeight: 600 }}>{item.name} <ArrowUpRight size={14} style={{ color: accent }} /></a>
              ) : (
                <span key={i} style={{ padding: ".5rem .9rem", borderRadius: 999, color: "var(--text-primary)", background: `color-mix(in srgb, ${accent} 10%, transparent)`, border: `1px solid color-mix(in srgb, ${accent} 32%, transparent)`, fontSize: ".85rem", fontWeight: 600 }}>{item.name}</span>
              ))}
            </div>
          </div>
        )}

        {ai && <p style={{ textAlign: "center", color: "var(--text-secondary)", fontSize: ".8rem", marginTop: "1.6rem" }}>{t("AI-curated real-world references — verify each before you rely on it.", "مراجع حقيقية منظّمة بالذكاء الاصطناعي — راجع كل واحدة قبل ما تعتمد عليها.")}</p>}
      </section>
      )}

      <PageNavigation currentPath="/kawwen-waayak" />
    </div>
  );
}
