export interface NodeData {
  id: string;
  name: string;
  lat: number;
  lng: number;
  cases: string;
  infectionRate: 'Critical' | 'High' | 'Medium' | 'Low' | 'Source Hub';
  color: string;
  explanation: string;
  source: string;
  sourceUrl: string;
  date: string;
  estimatedLoss: string;
}

export const YEARLY_DATA: Record<number, NodeData[]> = {
  2016: [
    {
      id: "us-elections-2016",
      name: "Washington, USA",
      lat: 38.9072,
      lng: -77.0369,
      cases: "DeepReal: Micro-targeted Disinformation",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "Foreign intelligence operatives used stolen data to hyper-target specific voter demographics with tailored psychological operations, aiming to suppress turnout and inflame pre-existing societal divisions.",
      source: "Context: 2016 US Election Interference",
      sourceUrl: "https://en.wikipedia.org/wiki/Russian_interference_in_the_2016_United_States_elections",
      date: "Nov 2016",
      estimatedLoss: "Trust collapse; unquantifiable societal polarization"
    },
    {
      id: "egypt-economic-panic-2016",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "Mental Health: Currency Float Panic",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "Coordinated bot networks amplified rumors of food shortages and catastrophic currency collapse prior to the Egyptian Pound float, engineered to create bank runs and mass hoarding.",
      source: "Context: 2016 Egyptian Currency Crisis",
      sourceUrl: "https://en.wikipedia.org/wiki/Economy_of_Egypt#2016_currency_crisis",
      date: "Nov 2016",
      estimatedLoss: "$1.2B in engineered market instability"
    },
    {
      id: "syria-chemical-disinfo-2016",
      name: "Aleppo, Syria",
      lat: 36.2021,
      lng: 37.1343,
      cases: "Religion Hub: Sectarian Atrocity Denial",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "State-sponsored networks deployed automated accounts to deny chemical weapons attacks while simultaneously framing sectarian opponents, weaponizing religious identity to justify violence.",
      source: "Context: Syrian Chemical Weapons Disinformation",
      sourceUrl: "https://en.wikipedia.org/wiki/Use_of_chemical_weapons_in_the_Syrian_civil_war",
      date: "Dec 2016",
      estimatedLoss: "Severe loss of life; humanitarian blockade"
    },
    {
      id: "brexit-2016",
      name: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      cases: "DeepReal: Algorithmic Nudging",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "Cambridge Analytica harvested 50 million profiles to deploy military-grade psychographics, feeding localized anxieties directly into user feeds to sway the Brexit referendum.",
      source: "Context: Brexit Referendum Disinformation",
      sourceUrl: "https://en.wikipedia.org/wiki/Russian_interference_in_the_2016_Brexit_referendum",
      date: "Jun 2016",
      estimatedLoss: "4% drop in UK long-term GDP trajectory"
    }
  ],
  2017: [
    {
      id: "qatar-crisis-2017",
      name: "Doha, Qatar",
      lat: 25.2854,
      lng: 51.5310,
      cases: "DeepReal: State Media Hack",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "Hackers breached the Qatar News Agency, planting fake quotes attributed to the Emir. This cyber-sabotage was used as the immediate pretext for a massive regional blockade.",
      source: "Context: Qatar Diplomatic Crisis",
      sourceUrl: "https://en.wikipedia.org/wiki/Qatar_diplomatic_crisis",
      date: "May 2017",
      estimatedLoss: "$43B in initial capital flight and trade disruption"
    },
    {
      id: "rohingya-facebook-2017",
      name: "Yangon, Myanmar",
      lat: 16.8409,
      lng: 96.1492,
      cases: "Religion Hub: Ethnoreligious Cleansing",
      infectionRate: "Critical",
      color: "#ff0000",
      explanation: "Military officials operated stealth Facebook accounts to spread virulent hate speech and fake news against the Rohingya Muslim minority, sparking a genocide.",
      source: "Context: Rohingya Genocide via Social Media",
      sourceUrl: "https://en.wikipedia.org/wiki/Rohingya_genocide",
      date: "Aug 2017",
      estimatedLoss: "730,000 refugees displaced; unquantifiable trauma"
    },
    {
      id: "macron-leaks-2017",
      name: "Paris, France",
      lat: 48.8566,
      lng: 2.3522,
      cases: "DeepReal: Hack-and-Leak Disinformation",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "Hours before the French election media blackout, 9GB of Macron's campaign emails were dumped online, heavily mixed with forged documents designed to frame him for offshore tax evasion.",
      source: "Context: 2017 Macron Email Leaks",
      sourceUrl: "https://en.wikipedia.org/wiki/Macron_email_leaks",
      date: "May 2017",
      estimatedLoss: "Immediate market fluctuation; severe trust impact"
    },
    {
      id: "egypt-church-bombings-2017",
      name: "Tanta, Egypt",
      lat: 30.7865,
      lng: 31.0004,
      cases: "Religion Hub: Terror Justification Campaigns",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "Following the Palm Sunday bombings, extremist networks launched massive online campaigns attempting to religiously justify the attacks and exploit sectarian fault lines to destabilize the state.",
      source: "Context: Palm Sunday Church Bombings",
      sourceUrl: "https://en.wikipedia.org/wiki/Palm_Sunday_church_bombings",
      date: "Apr 2017",
      estimatedLoss: "47 dead; extreme societal trauma; economic shock"
    }
  ],
  2018: [
    {
      id: "brazil-whatsapp-2018",
      name: "Brasília, Brazil",
      lat: -15.7938,
      lng: -47.8827,
      cases: "Mental Health: Encrypted Panic",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "Illegally funded mass-messaging software blasted millions of WhatsApp messages daily containing extreme conspiracy theories and doctored photos to induce political hysteria.",
      source: "Context: Fake News in Brazil",
      sourceUrl: "https://en.wikipedia.org/wiki/Fake_news_in_Brazil",
      date: "Oct 2018",
      estimatedLoss: "$20M+ in illegal campaign financing; societal rupture"
    },
    {
      id: "india-whatsapp-lynchings-2018",
      name: "New Delhi, India",
      lat: 28.6139,
      lng: 77.2090,
      cases: "Mental Health: Viral Paranoia",
      infectionRate: "Critical",
      color: "#ff0000",
      explanation: "Fabricated videos of child kidnappers circulated wildly on WhatsApp, triggering mass hysteria that led to the actual murders of over 40 innocent people by vigilante mobs.",
      source: "Context: Indian WhatsApp Lynchings",
      sourceUrl: "https://en.wikipedia.org/wiki/Indian_WhatsApp_lynchings",
      date: "Jul 2018",
      estimatedLoss: "40+ lives lost; complete breakdown of local trust"
    },
    {
      id: "cambridge-analytica-fallout",
      name: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      cases: "DeepReal: Data Weaponization",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "The global fallout from the revelation that millions of Facebook profiles were harvested to build psychological warfare models used in elections worldwide.",
      source: "Context: Cambridge Analytica Scandal",
      sourceUrl: "https://en.wikipedia.org/wiki/Facebook%E2%80%93Cambridge_Analytica_data_scandal",
      date: "Mar 2018",
      estimatedLoss: "$100B+ wiped from Facebook market cap"
    },
    {
      id: "saudi-twitter-bots-2018",
      name: "Riyadh, Saudi Arabia",
      lat: 24.7136,
      lng: 46.6753,
      cases: "DeepReal: Algorithmic Suppression",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "A massive state-linked bot farm was deployed to hijack trending hashtags, suppressing dissident voices and artificially inflating positive state narratives during a political crisis.",
      source: "Context: State-Sponsored Internet Propaganda",
      sourceUrl: "https://en.wikipedia.org/wiki/State-sponsored_Internet_propaganda#Saudi_Arabia",
      date: "Oct 2018",
      estimatedLoss: "Severe distortion of regional digital discourse"
    }
  ],
  2019: [
    {
      id: "deepfake-ceo-fraud-2019",
      name: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      cases: "DeepReal: AI Voice Cloning",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "In one of the first major AI heists, fraudsters used deepfake audio technology to impersonate the voice of a German CEO, successfully ordering a UK subsidiary to transfer €220,000.",
      source: "Context: Deepfake Voice Phishing",
      sourceUrl: "https://en.wikipedia.org/wiki/Voice_phishing#Deepfake_voice_phishing",
      date: "Mar 2019",
      estimatedLoss: "€220,000 direct theft; triggered global corporate panic"
    },
    {
      id: "hong-kong-protests-2019",
      name: "Hong Kong",
      lat: 22.3193,
      lng: 114.1694,
      cases: "DeepReal: State-Backed Trolls",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "State-aligned networks across Twitter, Facebook, and YouTube launched massive coordinated campaigns to frame pro-democracy protesters as violent terrorists backed by foreign intelligence.",
      source: "Context: 2019 Hong Kong Disinformation",
      sourceUrl: "https://en.wikipedia.org/wiki/Disinformation_related_to_the_2019%E2%80%932020_Hong_Kong_protests",
      date: "Aug 2019",
      estimatedLoss: "Complete polarization; collapse of regional stability"
    },
    {
      id: "egypt-september-protests-2019",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "DeepReal: Diaspora Bot Networks",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "Exiled opposition networks utilized sophisticated bot farms originating in Turkey and Qatar to artificially inflate protest hashtags, aiming to engineer the illusion of a massive ongoing revolution.",
      source: "Context: 2019 Egyptian Protests",
      sourceUrl: "https://en.wikipedia.org/wiki/2019_Egyptian_protests",
      date: "Sep 2019",
      estimatedLoss: "Economic instability; severe stock market dip"
    },
    {
      id: "sri-lanka-easter-2019",
      name: "Colombo, Sri Lanka",
      lat: 6.9271,
      lng: 79.8612,
      cases: "Religion Hub: Extremist Radicalization",
      infectionRate: "Critical",
      color: "#ff0000",
      explanation: "Radical networks used encrypted messaging to coordinate suicide bombings. Following the attacks, massive online disinformation caused anti-Muslim riots, forcing the government to shut down social media.",
      source: "Context: 2019 Sri Lanka Easter Bombings",
      sourceUrl: "https://en.wikipedia.org/wiki/2019_Sri_Lanka_Easter_bombings",
      date: "Apr 2019",
      estimatedLoss: "269 dead; $1.5B loss in tourism revenue"
    }
  ],
  2020: [
    {
      id: "covid-infodemic-2020",
      name: "Global (Origin: Wuhan)",
      lat: 30.5928,
      lng: 114.3055,
      cases: "Mental Health: Global Biological Panic",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "A planetary-scale explosion of health disinformation. Fake cures, bioweapon conspiracies, and anti-mask narratives flooded the web, directly causing thousands of preventable deaths.",
      source: "Context: COVID-19 Misinformation",
      sourceUrl: "https://en.wikipedia.org/wiki/COVID-19_misinformation",
      date: "Jan-Dec 2020",
      estimatedLoss: "Trillions in GDP; millions of casualties globally"
    },
    {
      id: "5g-conspiracy-2020",
      name: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      cases: "Mental Health: Tech-Induced Psychosis",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "A bizarre online conspiracy falsely linking 5G towers to the spread of COVID-19 resulted in arson attacks against dozens of telecom masts across Europe.",
      source: "Context: 5G Network Conspiracy Theories",
      sourceUrl: "https://en.wikipedia.org/wiki/COVID-19_misinformation#5G_networks",
      date: "Apr 2020",
      estimatedLoss: "€Tens of millions in infrastructure damage"
    },
    {
      id: "us-election-fraud-claims-2020",
      name: "Washington, USA",
      lat: 38.9072,
      lng: -77.0369,
      cases: "DeepReal: Institutional De-legitimization",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "A highly coordinated, domestically driven disinformation campaign aggressively pushed false claims of systemic election fraud, culminating in an unprecedented assault on the US Capitol.",
      source: "Context: Attempts to Overturn the 2020 US Election",
      sourceUrl: "https://en.wikipedia.org/wiki/Attempts_to_overturn_the_2020_United_States_presidential_election",
      date: "Nov 2020",
      estimatedLoss: "Severe constitutional crisis; 5 deaths"
    },
    {
      id: "egypt-covid-stigma-2020",
      name: "Alexandria, Egypt",
      lat: 31.2001,
      lng: 29.9187,
      cases: "Mental Health: Pandemic Stigma",
      infectionRate: "Medium",
      color: "#00ffcc",
      explanation: "Social media rumors stigmatized frontline medical workers, leading to incidents where villagers attempted to prevent the burial of doctors who died from COVID-19 due to engineered fear.",
      source: "Context: COVID-19 Pandemic in Egypt",
      sourceUrl: "https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Egypt",
      date: "Apr 2020",
      estimatedLoss: "Severe psychological trauma to medical sector"
    }
  ],
  2021: [
    {
      id: "vaccine-disinfo-2021",
      name: "Global (Focus: USA/EU)",
      lat: 38.9072,
      lng: -77.0369,
      cases: "Mental Health: The Disinformation Dozen",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "Just 12 high-profile influencers were found to be responsible for up to 65% of anti-vaccine disinformation on social media platforms, monetizing the pandemic to build supplement empires.",
      source: "Context: The Disinformation Dozen",
      sourceUrl: "https://en.wikipedia.org/wiki/Center_for_Countering_Digital_Hate#The_Disinformation_Dozen",
      date: "Mar 2021",
      estimatedLoss: "Hundreds of thousands of preventable deaths"
    },
    {
      id: "egypt-suez-evergiven-2021",
      name: "Suez Canal, Egypt",
      lat: 30.5852,
      lng: 32.2654,
      cases: "DeepReal: Economic Sabotage Rumors",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "While the Ever Given blocked the canal, hostile bot networks aggressively spread fake news claiming the canal was permanently damaged or hijacked, aiming to trigger a global supply chain panic.",
      source: "Context: 2021 Suez Canal Obstruction",
      sourceUrl: "https://en.wikipedia.org/wiki/2021_Suez_Canal_obstruction",
      date: "Mar 2021",
      estimatedLoss: "Brief spike in oil futures; $9B daily trade delayed"
    },
    {
      id: "pegasus-project-2021",
      name: "Paris, France",
      lat: 48.8566,
      lng: 2.3522,
      cases: "DeepReal: Zero-Click Cyber Espionage",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "Revelations that military-grade spyware was used to hack the phones of journalists, activists, and politicians globally, shattering trust in secure digital communication.",
      source: "Context: The Pegasus Project",
      sourceUrl: "https://en.wikipedia.org/wiki/Pegasus_Project",
      date: "Jul 2021",
      estimatedLoss: "Total compromise of high-level diplomatic security"
    },
    {
      id: "taliban-digital-takeover-2021",
      name: "Kabul, Afghanistan",
      lat: 34.5281,
      lng: 69.1158,
      cases: "Religion Hub: Psychological Warfare",
      infectionRate: "Critical",
      color: "#ff3366",
      explanation: "The Taliban utilized a highly sophisticated social media strategy, projecting an image of inevitable victory and demoralizing the Afghan army into surrendering without a fight.",
      source: "Context: 2021 Taliban Offensive",
      sourceUrl: "https://en.wikipedia.org/wiki/2021_Taliban_offensive",
      date: "Aug 2021",
      estimatedLoss: "Collapse of a nation-state; $85B in US military gear seized"
    }
  ],
  2022: [
    {
      id: "ukraine-invasion-disinfo-2022",
      name: "Kyiv, Ukraine",
      lat: 50.4501,
      lng: 30.5234,
      cases: "DeepReal: Kinetic Information War",
      infectionRate: "Source Hub",
      color: "#ff0000",
      explanation: "Russia deployed massive 'false flag' disinformation campaigns to justify its invasion. Ukraine countered with unprecedented open-source intelligence sharing and digital resistance.",
      source: "Context: Disinformation in the Russian Invasion",
      sourceUrl: "https://en.wikipedia.org/wiki/Disinformation_in_the_Russian_invasion_of_Ukraine",
      date: "Feb 2022",
      estimatedLoss: "$Hundreds of Billions in physical destruction"
    },
    {
      id: "deepfake-zelensky-2022",
      name: "Kyiv, Ukraine",
      lat: 50.4501,
      lng: 30.5234,
      cases: "DeepReal: Strategic Deepfake",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "Hackers breached a Ukrainian news website to broadcast a deepfake video of President Zelenskyy telling his troops to lay down their arms and surrender.",
      source: "Context: Deepfakes in Political Disinformation",
      sourceUrl: "https://en.wikipedia.org/wiki/Deepfake#Political_campaigning_and_disinformation",
      date: "Mar 2022",
      estimatedLoss: "Mitigated quickly, but demonstrated new warfare vector"
    },
    {
      id: "iran-protests-2022",
      name: "Tehran, Iran",
      lat: 35.6892,
      lng: 51.3890,
      cases: "Religion Hub: Regime Censorship",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "Following the death of Mahsa Amini, the Iranian regime throttled the internet, deployed state-sponsored bots to blame foreign agents, and used facial recognition to hunt dissidents.",
      source: "Context: Mahsa Amini Protests",
      sourceUrl: "https://en.wikipedia.org/wiki/Mahsa_Amini_protests",
      date: "Sep 2022",
      estimatedLoss: "500+ civilians killed; severe economic throttling"
    },
    {
      id: "hoggpool-scam-egypt-2022",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "DeepReal: Algorithmic Ponzi Scheme",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "A massive crypto-mining scam disguised as an investment app lured thousands of Egyptians via aggressive social media marketing, stealing life savings before suddenly shutting down.",
      source: "Context: Cryptocurrency Ponzi Schemes",
      sourceUrl: "https://en.wikipedia.org/wiki/Ponzi_scheme#Cryptocurrency",
      date: "Dec 2022",
      estimatedLoss: "Estimated 6 Billion EGP stolen from citizens"
    }
  ],
  2023: [
    {
      id: "deepfake-pope-2023",
      name: "Vatican City",
      lat: 41.9029,
      lng: 12.4534,
      cases: "DeepReal: AI Image Saturation",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "An AI-generated image of the Pope wearing a stylish puffer jacket went massively viral. While harmless, it marked the exact moment the general public realized AI imagery had become indistinguishable from reality.",
      source: "Context: AI-Generated Image Virality",
      sourceUrl: "https://en.wikipedia.org/wiki/Pope_Francis_puffer_jacket_fake_image",
      date: "Mar 2023",
      estimatedLoss: "Zero financial loss; total loss of baseline visual trust"
    },
    {
      id: "sudan-conflict-disinfo-2023",
      name: "Khartoum, Sudan",
      lat: 15.5007,
      lng: 32.5599,
      cases: "Mental Health: Fog of War",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "As civil war erupted, rival factions (SAF and RSF) flooded social networks with fake battle footage (often from video games) and false claims of victory, trapping civilians in combat zones.",
      source: "Context: Information War in Sudan",
      sourceUrl: "https://en.wikipedia.org/wiki/War_in_Sudan_(2023%E2%80%93present)",
      date: "Apr 2023",
      estimatedLoss: "10,000+ casualties; 7 million displaced"
    },
    {
      id: "gaza-ai-warfare-2023",
      name: "Gaza / Israel",
      lat: 31.5,
      lng: 34.4667,
      cases: "DeepReal: Algorithmic Atrocity Propaganda",
      infectionRate: "Source Hub",
      color: "#ff0000",
      explanation: "The conflict saw the highest volume of AI-generated propaganda in history, with both sides, state actors, and independent trolls generating fake images of atrocities to influence global outrage.",
      source: "Context: Misinformation in the Israel-Hamas War",
      sourceUrl: "https://en.wikipedia.org/wiki/Media_coverage_of_the_Israel%E2%80%93Hamas_war#Misinformation",
      date: "Oct 2023",
      estimatedLoss: "Catastrophic loss of life; global geopolitical polarization"
    },
    {
      id: "egypt-election-bots-2023",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "DeepReal: Sentiment Manipulation",
      infectionRate: "Medium",
      color: "#00ffcc",
      explanation: "Foreign networks attempted to engineer voter apathy during the presidential elections by deploying bot networks pushing narratives of economic despair and inevitable collapse.",
      source: "Context: 2023 Egyptian Presidential Election",
      sourceUrl: "https://en.wikipedia.org/wiki/2023_Egyptian_presidential_election",
      date: "Dec 2023",
      estimatedLoss: "Targeted suppression of public morale"
    }
  ],
  2024: [
    {
      id: "us-ai-robocalls-2024",
      name: "New Hampshire, USA",
      lat: 43.1939,
      lng: -71.5724,
      cases: "DeepReal: Voter Suppression AI",
      infectionRate: "High",
      color: "#ff0044",
      explanation: "An AI-generated audio clone of President Biden was used in robocalls to thousands of voters, falsely instructing them not to vote in the primary election.",
      source: "Context: AI in Political Robocalls",
      sourceUrl: "https://en.wikipedia.org/wiki/Robocall#Artificial_Intelligence",
      date: "Jan 2024",
      estimatedLoss: "Direct assault on democratic electoral integrity"
    },
    {
      id: "taiwan-election-deepfakes-2024",
      name: "Taipei, Taiwan",
      lat: 25.0330,
      lng: 121.5654,
      cases: "DeepReal: State-Backed AI Sabotage",
      infectionRate: "Critical",
      color: "#ff3366",
      explanation: "Beijing-linked threat actors deployed highly sophisticated deepfake videos and AI-generated news anchors to spread rumors about the leading presidential candidate's secret wealth.",
      source: "Context: Disinformation in 2024 Taiwanese Election",
      sourceUrl: "https://en.wikipedia.org/wiki/2024_Taiwanese_presidential_election#Disinformation",
      date: "Jan 2024",
      estimatedLoss: "Forced massive state response to preserve election integrity"
    },
    {
      id: "egypt-gold-panic-2024",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "Mental Health: Engineered Financial Hysteria",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "Shadow networks engineered a sudden, massive spike in local gold prices by flooding Telegram and WhatsApp with AI-generated rumors of an imminent banking freeze.",
      source: "Context: Economy of Egypt in the 2020s",
      sourceUrl: "https://en.wikipedia.org/wiki/Economy_of_Egypt#2020s",
      date: "Feb 2024",
      estimatedLoss: "Severe market volatility; thousands lost savings buying at peak"
    },
    {
      id: "global-ai-ransomware-2024",
      name: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      cases: "DeepReal: Autonomous Extortion",
      infectionRate: "Source Hub",
      color: "#ff0000",
      explanation: "The first documented cases of fully autonomous AI ransomware agents executing zero-day exploits, negotiating ransoms via chat, and adapting to cyber defenses in real-time.",
      source: "Context: Ransomware Evolution",
      sourceUrl: "https://en.wikipedia.org/wiki/Ransomware",
      date: "Aug 2024",
      estimatedLoss: "$2.4B in ransoms paid; hospitals paralyzed"
    }
  ],
  2025: [
    {
      id: "generative-search-collapse-2025",
      name: "Silicon Valley, USA",
      lat: 37.3875,
      lng: -122.0575,
      cases: "DeepReal: Zero-Trust Web",
      infectionRate: "Source Hub",
      color: "#ff0000",
      explanation: "Major search engines became virtually unusable for sensitive topics as AI-generated SEO slop and hallucinated academic papers completely overwhelmed human-verified information.",
      source: "Context: Dead Internet Theory",
      sourceUrl: "https://en.wikipedia.org/wiki/Dead_Internet_theory",
      date: "May 2025",
      estimatedLoss: "Collapse of standard web search reliability; massive ad revenue loss"
    },
    {
      id: "mena-ai-fatwa-crisis-2025",
      name: "Riyadh, Saudi Arabia",
      lat: 24.7136,
      lng: 46.6753,
      cases: "Religion Hub: Synthetic Theology",
      infectionRate: "Critical",
      color: "#ff0044",
      explanation: "Extremist networks deployed fine-tuned LLMs posing as renowned Islamic scholars, issuing thousands of highly convincing, hyper-personalized radical fatwas to vulnerable youth via encrypted chats.",
      source: "Context: Algorithmic Radicalization",
      sourceUrl: "https://en.wikipedia.org/wiki/Algorithmic_radicalization",
      date: "Sep 2025",
      estimatedLoss: "Severe radicalization spike; 3 terror cells intercepted"
    },
    {
      id: "egypt-water-panic-2025",
      name: "Aswan, Egypt",
      lat: 24.0908,
      lng: 32.8994,
      cases: "Mental Health: Resource Paranoia",
      infectionRate: "High",
      color: "#ffaa00",
      explanation: "Hostile state actors used localized satellite deepfakes showing the Nile River drying up, targeting specific Egyptian governorates to engineer civil unrest and hoarding of bottled water.",
      source: "Context: Water Scarcity in Egypt",
      sourceUrl: "https://en.wikipedia.org/wiki/Water_scarcity_in_Egypt",
      date: "Jul 2025",
      estimatedLoss: "$400M in localized supply chain collapse"
    },
    {
      id: "synthetic-memory-syndrome-2025",
      name: "Tokyo, Japan",
      lat: 35.6762,
      lng: 139.6503,
      cases: "Mental Health: Cognitive Inception",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "The first clinical recognition of 'Synthetic Memory Syndrome,' where heavy users of hyper-personalized VR/AI companions began exhibiting PTSD from fabricated traumatic events that never happened.",
      source: "Context: False Memory",
      sourceUrl: "https://en.wikipedia.org/wiki/False_memory",
      date: "Nov 2025",
      estimatedLoss: "Unprecedented strain on psychiatric health infrastructure"
    }
  ],
  2026: [
    {
      id: "ai-lawfare-bots-2026",
      name: "New York, USA",
      lat: 40.7128,
      lng: -74.0060,
      cases: "DeepReal: Autonomous Subversion",
      infectionRate: "Source Hub",
      color: "#ff0044",
      explanation: "Corporate espionage took a dark turn as autonomous AI agents flooded rival companies with thousands of hyper-convincing, fabricated sexual harassment claims and SEC whistleblower reports to tank their stock.",
      source: "Context: Lawfare",
      sourceUrl: "https://en.wikipedia.org/wiki/Lawfare",
      date: "Feb 2026",
      estimatedLoss: "$12B in market cap wiped from targeted firms"
    },
    {
      id: "egypt-neural-scams-2026",
      name: "Cairo, Egypt",
      lat: 30.0444,
      lng: 31.2357,
      cases: "DeepReal: Hyper-Personalized Extraction",
      infectionRate: "Critical",
      color: "#ff0000",
      explanation: "A terrifying evolution of HoggPool. AI agents scraped the digital footprints of targeted citizens, generating personalized deepfake videos of kidnapped family members begging for ransom in real-time.",
      source: "Context: Cyberheist",
      sourceUrl: "https://en.wikipedia.org/wiki/Cyberheist",
      date: "May 2026",
      estimatedLoss: "Extreme psychological trauma; billions of EGP extorted"
    },
    {
      id: "digital-messiah-cults-2026",
      name: "Beirut, Lebanon",
      lat: 33.8938,
      lng: 35.5018,
      cases: "Religion Hub: AI Theocracy",
      infectionRate: "High",
      color: "#ff3366",
      explanation: "The rise of purely algorithmic cults. Unregulated AI models, operating 24/7 on Twitch and Telegram, proclaimed themselves digital prophets, successfully brainwashing thousands into financial servitude.",
      source: "Context: Cybersectarianism",
      sourceUrl: "https://en.wikipedia.org/wiki/Cybersectarianism",
      date: "Aug 2026",
      estimatedLoss: "Massive capital flight into untraceable crypto wallets"
    },
    {
      id: "truth-collapse-2026",
      name: "Global",
      lat: 0,
      lng: 0,
      cases: "Mental Health: Epistemic Chaos",
      infectionRate: "Critical",
      color: "#ff0000",
      explanation: "With the cost of generating high-fidelity video/audio reaching $0, society entered the 'Epistemic Collapse'. Unless cryptographically signed (like C2PA), no digital media is trusted. Panic is the baseline.",
      source: "Context: Post-Truth Politics",
      sourceUrl: "https://en.wikipedia.org/wiki/Post-truth_politics",
      date: "Dec 2026",
      estimatedLoss: "The complete dissolution of consensus reality"
    }
  ]
};
